module.exports = {
    present_index_page: function(){
        var html = '';
    
        html = '<html class="yui3-js-enabled" lang="en">';
        html += '<div id="yui3-css-stamp" style="position: absolute !important; visibility: hidden !important"></div><head></head><body class="signin" yahoo-adbuilder="loaded"><div class="alert alert-success fade in"> <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a> <strong>SUCCESS: </strong> You were just logged out.</div> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"> <meta name="description" content=""> <meta name="author" content=""> <link rel="shortcut icon" href="images/favicon.png" type="image/png"> <title>SPYR Games Admin</title> <link href="http://localhost:8888/SPYRDashboardv1/css/style.default.css" rel="stylesheet"> <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries --> <!--[if lt IE 9]> <script src="js/html5shiv.js"></script> <script src="js/respond.min.js"></script> <![endif]--> <section> <div class="signinpanel"> <div class="row"> <div class=" col-md-offset-4 col-md-8"> <div class="signin-info"> <div class="logopanel"> <h1>SPYR Games</h1> </div><!-- logopanel --> <div class="mb20"></div> <h5><strong>Sign in to access your dashboard</strong></h5> </div><!-- signin0-info --> </div><!-- col-sm-7 --> <div class="col-md-offset-2 col-md-8"> <form method="post" action="/SPYRDashboardv1/loginform.php" name="loginform"> <h4 class="nomargin">Sign In</h4> <p class="mt5 mb20">Login to access your account.</p> <input id="login_input_username" name="user_name" type="text" class="form-control uname" placeholder="Username" required="" style="background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGP6zwAAAgcBApocMXEAAAAASUVORK5CYII=);" autocomplete="off"> <input id="login_input_password" name="user_password" type="password" class="form-control pword" placeholder="Password" required="" style="background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGP6zwAAAgcBApocMXEAAAAASUVORK5CYII=);" autocomplete="off"> <a href=""><small>Forgot Your Password?</small></a> <input class="btn btn-success btn-block" type="submit" name="login" value="Log in"> <a class="btn btn-default btn-block" href="/SPYRDashboardv1/loginform.php?action=register">Register new account</a> </form> </div><!-- col-sm-5 --> </div><!-- row --> <div class="signup-footer"> <div class="pull-left"> Data Contained  © 2015. All Rights Reserved. SPYR Games.  </div> </div> </div><!-- signin --> ';
    
        return html;
    },
};


